# https://www.howtogeek.com/devops/how-to-run-mysql-in-a-docker-container/
version: "3"

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: